nous_aggregator/urls.py
from typing import List

from decouple import config
from django.contrib import admin
from django.urls import include, path
from django.urls.resolvers import URLResolver

urlpatterns: List[URLResolver] = [
    path("", include("articles.urls")),
    path("articles", include("articles.urls")),
    path("", include("articles.urls")),
    path("admin/", admin.site.urls),
]


if config("DJANGO_ENV", default="BASE") == "LOCAL":
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

src/articles/urls.py
from typing import List

from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

urlpatterns: List[URLPattern] = [
    path("", views.index, name="index"),
    path("search", views.SearchResultsView.as_view(), name="search"),
]

src/articles/models.py
import regex
from django.db import models
from django.db.models.functions import Lower
from django.utils.translation import gettext_lazy as _

from .constants import Language, PublicationType


class Article(models.Model):
    """
    Metadata about articles from newspapers, journals, etc.

    Fields:
        title (models.TextField): headline of the article
        slug (models.SlugField): slug of the article (generated from title)
        description (models.TextField): short paragraph summarizing the article
        created_at (models.DateTimeField): date the article was added to the
            database. Either the publication date (from RSS feed) or the time
            the article was created (if the article is scraped; the publication
            date is difficult to obtain in this case)
        language (models.CharField): the language of the article
        url (models.URLField): link to the article

    Relations:
        source (ForeignKey): the source of the article

    Methods:
        __str__: string representation for the admin area
    """

    title = models.CharField(
        max_length=512,
        help_text=_("The headline of the article"),
    )
    slug = models.SlugField(
        max_length=1024,
        help_text=_("The slug of the article for SEO-friendly urls"),
    )
    description = models.TextField(
        blank=True,
        help_text=_("A description/summary of the article"),
    )
    created_at = models.DateTimeField()
    language = models.CharField(
        max_length=16,
        choices=Language.choices,
        blank=False,
        help_text=_("The language of the article"),
    )
    url = models.URLField(
        max_length=512,
        unique=True,
        help_text=_("The link to the article"),
    )
    source = models.ForeignKey(
        to="Source",
        on_delete=models.CASCADE,
        related_name="articles",
        help_text=_("The source where the article is published"),
    )

    class Meta:
        ordering = ("-created_at",)
        indexes = [models.Index(fields=["title", "url"])]

    def __str__(self) -> str:
        return f"{self.source}: {self.title}"


class Source(models.Model):
    """
    Metadata about the source of articles

    Fields:
        title (models.CharField): name/title of the source
        slug (models.SlugField): slug of the source
        publication_type (models.CharField): the type of publication of the
            source (newspaper, journal, blog...)
        language (models.CharField): the language of the source
        url (models.URLField): the base url of the source

    Relations:
        sitemap (models.OneToOneField): information about the HTML/CSS structure
            of the page required for scraping

    Methods:
        __str__: string representation of the model for the admin area
    """

    title = models.CharField(
        max_length=128,
        unique=True,
        blank=False,
        help_text=_("The name of the source"),
    )
    slug = models.SlugField(
        max_length=255,
        blank=True,
        help_text=_("The slug of the source for SEO-friendly urls"),
    )
    publication_type = models.CharField(
        max_length=24,
        choices=PublicationType.choices,
        blank=False,
        help_text=_("The type of publication of the source"),
    )
    language = models.CharField(
        max_length=16,
        choices=Language.choices,
        blank=True,
        help_text=_("The language of the article"),
    )
    url = models.URLField(
        unique=True,
        max_length=512,
        help_text=_("The url of the source"),
    )

    class Meta:
        ordering = [
            Lower("title"),
        ]

    def __str__(self) -> str:
        return f"{self.title}"


class Sitemap(models.Model):
    """Information for scraping source"""

    source = models.OneToOneField(
        to=Source,
        on_delete=models.CASCADE,
    )
    paths = models.JSONField(
        help_text=_(
            "List of resource paths where the scraper will look for articles"
        ),
    )
    regex = models.CharField(
        max_length=255,
        blank=True,
        help_text=(
            "Regular expression for filtering hyper-links found at the resource paths"
        ),
    )
    javascript_required = models.BooleanField(
        default=False,
        help_text=_(
            "Whether the parsing of articles by this source requires rendering "
            "of JavaScript"
        ),
    )
    title_search_params_find = models.JSONField(
        default=str,
        help_text=_(
            "Selectors for extracting the headline of articles"
        ),
    )
    title_search_params_remove = models.JSONField(
        null=True,
        blank=True,
        help_text=_(
            "Selectors for HTML elements that need to be removed from the headline"
        ),
    )
    description_search_params_find = models.JSONField(
        default=str,
        help_text=_(
            "Selectors for extracting the summary of articles"
        ),
    )
    description_search_params_remove = models.JSONField(
        null=True,
        blank=True,
        help_text=_(
            "Selectors for HTML elements that need to be removed from the summary"
        ),
    )

    def to_dict(self):
        return {
            "base_url": self.source.url,
            "paths": self.paths,
            "language": self.source.language,
            "javascript_required": self.javascript_required,
            "filter": regex.compile(self.regex),
            "search_params": {
                "title": {
                    "find": self.title_search_params_find,
                    "remove": self.title_search_params_remove,
                },
                "description": {
                    "find": self.description_search_params_find,
                    "remove": self.description_search_params_remove,
                },
            },
        }


class Feed(models.Model):
    source = models.ForeignKey(
        to=Source,
        on_delete=models.CASCADE,
        related_name="feeds",
    )
    url = models.URLField(
        unique=True,
        max_length=512,
        help_text=_("The url of the RSS feed"),
    )

src/articles/views.py
import re
from typing import Any, Dict, Optional

from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from .models import Article, Source


def index(request: Optional[HttpRequest]) -> HttpResponse:
    context = {
        "sources": Source.objects.only("title", "url", "publication_type"),
    }
    return render(request, "articles/index.html", context)


class SearchResultsView(ListView):
    model = Article
    fields = ["title", "url", "body"]
    template_name = "articles/search_results.html"

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        """Pre-filter sources on the basis of article headlines and queries"""

        context = super().get_context_data(**kwargs)

        query = self.request.GET.get("q")
        if query and not query.isspace():
            regex = r"(?<![a-zA-Z])" + re.escape(query) + r"(?![a-rA-Rt-zT-Z])"
            context.update(
                {
                    "sources": Source.objects.only("title", "url", "publication_type")
                                             .filter(articles__title__iregex=regex)
                                             .distinct(),
                    "query": query,
                },
            )
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        regex = r"(?<![a-zA-Z])" + re.escape(query) + r"(?![a-rA-Rt-zT-Z])"
        return Article.objects.filter(title__iregex=regex)

src/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Meta tags -->
    <meta name="description"
    	  content="A news aggregator that collects and displays meta-data about articles from various sources.">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  </head>
  <body>
    {% include "articles/navbar.html" %}

    <div class="container main-container">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

src/articles/templates/articles/index.html
{% extends "articles/base.html" %}
{% load static humanize strip_html_tags %}

{% block title %}Nous Aggregator{% endblock %}

{% block content %}
<div class="container container-sources">
  <div class="row">
    {% for source in sources %}
      <div class="col-md-12 col-lg-6 col-xl-4 container-articles-outer">
	<div class="source"><a class="source-link" href="{{ source.url }}"><h5 class="source-title">{{ source.title }}</h5></a></div>
	<div class="container-articles-inner">
	<ul class="article-list">
	  {% for article in source.articles.all|slice:":10" %}
	    <li>
	      <div class="article-headline">
            <a class="article-link main-text"
               title="{{article.title}}&#10;&#10;{{ article.description|slice:":200"|strip_html_tags}}...&#10;&#10;{{article.created_at|naturaltime}}"
               href="{{ article.url }}">{{ article.title}}
            </a>
	      </div>
	    </li>
	    <hr>
	  {% endfor %}
	</ul>
	</div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

src/articles/templates/articles/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Nous Aggregator</a>

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <!-- Links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>

      <!-- Search -->
      <form class="d-flex" role="search" action="{% url 'search' %}" method="GET">
        <input class="form-control me-2 search-field" name="q" type="text"
	       required pattern=".*\S+.*" title="at least one non-space character"
	       placeholder="Search..." aria-label="Search" {% if query %} value={{ query }} {% endif %}>
	<button class="btn btn-outline-success search-button" type="submit">Search</button>
	<a class="undo-button" href="{% url "index" %}"><i class="fa fa-undo"></i></a>
      </form>
    </div>
  </div>
</nav>

src/articles/templates/articles/search_results.html
{% extends "articles/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}Nous Aggregator{% endblock %}

{% block content %}
<div class="container container-sources">
  {% if query %}
      <h3>Search Results for: "{{ query }}"</h3>
  {% endif %}
  <div class="row">
    {% for source in sources %}
      <div class="col-md-12 col-lg-6 col-xl-4 container-articles-outer">
	<div><a class="source-link" href="{{ source.url }}"><h5 class="source-title">{{ source.title }}</h5></a></div>
	<div class="container-articles-inner container-scrolling">
	<ul>
	  {% for article in article_list %}
	    {% if article.source.title == source.title %}
	    <li>
	      <div class="article-headline">
		<a class="article-link main-text"
		   title="{{ article.title }}&#10;&#10;{{ article.description|slice:":200" }}...&#10;&#10;{{ article.created_at|naturaltime }}"
		   href="{{ article.url }}">{{ article.title}}
		</a>
	      </div>
	    </li>
	    <hr>
	    {% endif %}
	  {% endfor %}
	</ul>
	</div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}